# Usa a imagem oficial do OpenJDK 17
FROM openjdk:17-jdk-slim

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o arquivo JAR do projeto para dentro do contêiner
COPY target/GerenciadorEscolar-0.0.1-SNAPSHOT.jar app.jar

# Expõe a porta 8090 para o ambiente externo
EXPOSE 8090

# Define o comando para rodar a aplicação Spring Boot
ENTRYPOINT ["java", "-jar", "app.jar"]
