version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_gerenciador_escolar
    restart: always
    environment:
      MYSQL_DATABASE: gerenciador_escolar
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gerenciador_network

  backend:
    build: .
    container_name: backend_gerenciador_escolar
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gerenciador_escolar?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
      SERVER_PORT: 8090
    ports:
      - "8090:8090"
    depends_on:
      - mysql
    networks:
      - gerenciador_network

networks:
  gerenciador_network:

volumes:
  mysql_data:
