jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:"sua_chave_acesso_super_segura"}
  refresh:
    secret: ${JWT_REFRESH_SECRET:"sua_chave_refresh_super_segura"} #fazer usar
    expiration: ${JWT_REFRESH_EXPIRATION:604800000} # Expiração do refresh token (7 dias em milissegundos)


minio:
  base:
    url: ${MINIO_API_URL:http://localhost:8080/api/media}
  api:
    key: ${MINIO_API_KEY:123}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}

  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQL8Dialect}
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8090}
